# Generated by Django 6.0.2 on 2026-05-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='category',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='MyApp1.category'),
            preserve_default=b'I01\n',
        ),
    ]
